/*
DDL 실습문제
*/
DROP TABLE TB_CATEGORY;
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(20),
    USE_YN CHAR(1) 
);
INSERT INTO TB_CATEGORY VALUES('박지은','Y');

SELECT*FROM TB_CATEGORY;

CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

--3번 

ALTER TABLE TB_CATEGORY ADD PRIMARY KEY(NAME);

-- 4번
-- TB_CLASS_TYPE 테이블의 NAME컬럼에 NOT NULL 
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;

--5번
-- 두 테이블에서 컬럼명 NO 기존타입유지하면서 크기를 10으로 NAME인것은 크기20으로
ALTER TABLE TB_CATEGORY
MODIFY NAME VARCHAR2(20);

ALTER TABLE TB_CLASS_TYPE
MODIFY NO VARCHAR2(10);

--6 두 테이블 NO와 NAME컬럼의 이름을 각각 TB를 제외한 테이블 이름이 앞에 붙은 형태로 변경한다.

ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_TYPE_NO;
