SELECT DEPARTMENT_NAME,CATEGORY
FROM tb_department;

SELECT DEPARTMENT_NAME||'의 정원은'|| CAPACITY||'명 입니다.'"학과별 정원"
FROM tb_department;

-- 3번 국문학과에 다니는 여학생 중 휴학한 학생 
SELECT DEPARTMENT_NO
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '국어국문학과';


SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_SSN, 8, 1) = '2' AND
    ABSENCE_YN = 'Y' AND DEPARTMENT_NO = 001;




-- 10번
SELECT STUDENT_NO,STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'N' AND TO_CHAR(STUDENT_NO) LIKE '_2_____' 
                       AND STUDENT_ADDRESS LIKE '전주%';

