SELECT DEPARTMENT_NAME,CATEGORY
FROM tb_department;

SELECT DEPARTMENT_NAME||'의 정원은'|| CAPACITY||'명 입니다.'"학과별 정원"
FROM tb_department;


-- 10번
SELECT STUDENT_NO,STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'N' AND TO_CHAR(STUDENT_NO) LIKE '_2_____' AND STUDENT_ADDRESS LIKE '전주%';

